# Generated by Django 2.0 on 2018-11-20 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AES', models.CharField(blank=True, max_length=100, null=True)),
                ('RSA_Public', models.CharField(blank=True, max_length=100, null=True)),
                ('RSA_Private', models.CharField(blank=True, max_length=100, null=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='ctime',
            field=models.DateTimeField(auto_now=True, verbose_name=django.db.models.fields.DateTimeField),
        ),
    ]
