# Generated by Django 2.0 on 2019-01-14 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181120_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dprotocol',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
