# Generated by Django 2.0 on 2019-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_device_dprotocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkey',
            name='AES',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='RSA_Private',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='RSA_Public',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
