# Generated by Django 2.0 on 2019-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190203_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rulers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='devices', to='company.DeviceRuler'),
        ),
    ]
