# Generated by Django 2.0 on 2019-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_device_rulers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permission', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='permission',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='permission',
            field=models.ManyToManyField(default=None, related_name='userinfo', to='company.UserPerm'),
        ),
    ]
