# Generated by Django 2.0 on 2018-10-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zigbee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZigbeeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('state', models.CharField(default='normal', max_length=50)),
                ('zigbee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='zigbee.Zigbee')),
            ],
        ),
    ]
