# Generated by Django 2.0 on 2018-10-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zigbee',
            name='english',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
