# Generated by Django 2.0 on 2018-10-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0002_zigbee_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZigbeeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('ctime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('newstate', models.CharField(max_length=50)),
                ('zigbee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zigbee_action', to='zigbee.Zigbee')),
                ('zigbee_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zigbee_state', to='zigbee.ZigbeeState')),
            ],
        ),
    ]
