# Generated by Django 2.0 on 2018-10-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0003_zigbeeaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zigbeeaction',
            name='zigbee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zigbee.Zigbee'),
        ),
        migrations.AlterField(
            model_name='zigbeeaction',
            name='zigbee_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zigbee.ZigbeeState'),
        ),
    ]
