# Generated by Django 2.0 on 2018-11-19 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0005_zigbeeaction_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='zigbee',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('6e9b2bfa-ebd7-11e8-a526-fcaa14cc1e81'), null=True),
        ),
    ]
