# Generated by Django 2.0 on 2018-11-20 07:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0006_zigbee_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zigbeestate',
            name='state_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zigbee',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('aecc5f92-ec96-11e8-b8cc-a41f725085cb'), null=True),
        ),
    ]
