# Generated by Django 2.0 on 2018-11-30 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0007_auto_20181120_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zigbee',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('38c697d8-f442-11e8-93b3-a41f725085cb'), null=True),
        ),
    ]
