# Generated by Django 2.0 on 2019-01-03 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zigbee', '0008_auto_20181130_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zigbee',
            old_name='english',
            new_name='ename',
        ),
        migrations.AlterField(
            model_name='zigbee',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.UUID('faef71d2-0f08-11e9-a949-fcaa14cc1e81'), null=True),
        ),
    ]
